
services:
  - type: web
    name: swift-web-sender
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    branch: main
    autoDeploy: true
